version: "3.8"

services:
  fastapi:
    build:
      context: ./fastapi
    ports:
      - "8000:8000"
    networks:
      - feddits_default
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  streamlit:
    build:
      context: ./streamlit
    ports:
      - "8501:8501"
    depends_on:
      fastapi:
        condition: service_healthy
    networks:
      - feddits_default

networks:
  feddits_default:
    external: true
